# Generated by Django 4.1.7 on 2023-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_dish_alter_profile_options_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/%y/%m%d')),
                ('first_title', models.CharField(max_length=100)),
                ('span_title', models.CharField(max_length=100)),
                ('last_title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Carousel Table',
            },
        ),
    ]
